# name: Deploy to Github pages
# on:
#   push:
#     branches: [dist]
# env:
#   BUILD_FOLDER: .output/public

# jobs:
#   build:
#     runs-on: ubuntu-lates
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Generate static ...
#         uses: actions/setup-node@v3
#         with:
#           node-version: "16"
#           cache: 'yarn'
#       - run: |
#           # yarn install
#           # yarn generate
#       - name: Init new repo in $BUILD_FOLDER and commit generated files
#         run: |
#           grep -rnwl "<link rel=\"prefetch\"" $BUILD_FOLDER | xargs sed -i 's$<link rel="prefetch" href="[^"]*\.\(jpg\|png\|webm\|jpeg\|svg\|gif\)">$$g'
#           cd $BUILD_FOLDER
#           touch .nojekyll
#           git init
#           git add -A
#           git config --local user.email "action@github.com"
#           git config --local user.name "Github Action"
#           git commit -m 'deploy'
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           folder: ${{env.BUILD_FOLDER}}

# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      # Pick your own package manager and build script
      #- run: npm install
      #- run: npx nuxt build --preset github_pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4